# Generated by Django 2.2.12 on 2021-02-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_doctor_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('complication', models.CharField(default='', max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=30)),
                ('patient', models.CharField(max_length=30)),
                ('prescription', models.CharField(max_length=500)),
            ],
        ),
    ]
