# Generated by Django 2.2.12 on 2021-02-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='hospital',
        ),
    ]
